version: "3.8"

services:
  webapp:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: webapp:django
    container_name: django_container
    command: python ./linear/manage.py runserver 0.0.0.0:8000